### ISSUE TITLE
Visual Studio Designer: Timed out while connecting to named pipe. 

### ISSUE THREAD

**Issue by tommai78101** [dotnet/docs-desktop#1424]
The article linked to this issue does not mention anything about a "named pipe".

I received an error message mentioning this:

```
Timed out while connecting to named pipe. 

Instances of this error (1)  
 
1.   Hide Call Stack 
 
at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<>c__DisplayClass24_1.<<-ctor>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__26.MoveNext()  
```

And here's the attachment to reproduce the error:

[Application.zip](https://github.com/dotnet/docs-desktop/files/9126958/Application.zip)

This ZIP file contains the full Visual Studio 2022 solution that will produce the error.

What do I do to fix this issue? I would like to request for someone to add this error to this page, as well as the steps to resolve this problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1d72f14-cf02-36b6-9448-9617839ba915
* Version Independent ID: f0ac6a95-eac8-64df-6bd8-d508e4103332
* Content: [Design-time errors in the Windows Forms Designer](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/design-time-errors-in-the-windows-forms-designer?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(DTELErrorList)%26rd%3Dtrue&view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/design-time-errors-in-the-windows-forms-designer.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/design-time-errors-in-the-windows-forms-designer.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@tommai78101 Hi there. Did you use the **Help** > **Send Feedback** > **Report a Problem...** feature of Visual Studio? This can capture your Visual Studio settings/environment/and you can upload code directly to the product team to help figure out what is broken.

There isn't really anything I can do to triage and figure out what the problem is, I can only add details to this article about the problem and fix (when found). Please use the feedback feature of Visual Studio and then report back to me if there is something to adjust in the documentation.

Sorry!

**Comment by tommai78101** [comment]
@adegeo That is the whole purpose of this ticket. I would like to request the documentation to be updated so it includes this entry about a "Timed out while connecting to named pipe".
